### ISSUE TITLE
Feature Request: Non Applicable Option

### ISSUE THREAD

**Issue by Kyle-Lahure** [platisd/definition-of-done#39]
This Action is great and we just started implementing it into our pr workflow. One thing that would be great in the future would be to have the ability for the user filling out the definition of done to be able to mark some items as non applicable to the changes made in thier pr.

**Comment by platisd** [comment]
Interesting use case.
I haven't tried this, but would it work if whoever is checking boxes out to edit the PR description and manually add a "tag", e.g. `[NOT APPLICABLE]` at the end of the related bulletpoint?

Not sure how to "automate" this. Let me know if you have any ideas. 

Otherwise we could make bulletpoints "optional", but that would be project-wide and not on per-PR basis.

**Comment by Kyle-Lahure** [comment]
Manually adding a tag would work, Currently I have my team doing something similar but then checking the box so the action passes.

Our project contains both front and backend so our DOD changes a bit depending what was worked on, and like you said since this is project wide we have them formatted with the indentations to seperate the sections but in order for the script to pass both need to be checked.

Maybe a more elegant way would be to have a "Header" with a dropdown next to it with options for the section eg.(Not Applicable) or even another check box that if unchecked the script passes over that section.

The other option I'm investigating is to check the path of the files changed in the pr in my workflow and have seperate dod.yaml's based on what's been changed and direct your action to the appropriate checklist based on that.

If my usecase doesn't make to much sense though and you have another suggestion, im all ears haha

**Comment by platisd** [comment]
I am thinking of adding a way for the PR author to choose which DoD they'd like to use for their PR (if not the default one). Would this solve this issue?
E.g. instead of setting items as non-applicable, you could choose a different DoD depending on what's worked on in the particular PR.

My current thought is to "override" the default DoD configuration via a special comment at the end of the PR text, where the PR author can specify another local path for their DoD.
Feel free to share your thoughts on this.

**Comment by platisd** [comment]
Closing this since support for optional tags was also added as of #43: 

> * (Optional) `optional_tag`: A tag that if found in a DoD checklist item in its beginning or end, will denote that
  the specific item is optional. The tag will **not** be removed from the item, but it will be ignored when checking
  if the DoD is satisfied.
>    * Example: `optional_tag: "[OPTIONAL]"` will make the action ignore items like `"[OPTIONAL] Checklist item 1"`.
